artifact_location: file:///home/duds0/agents/projects/full-funnel-ai-analytics/ml/mlflow/950969965343710583
creation_time: 1773583831621
experiment_id: '950969965343710583'
last_update_time: 1773583831621
lifecycle_stage: active
name: Lead Scoring Optimization
workspace: default
