artifact_location: file:///home/duds0/agents/projects/full-funnel-ai-analytics/ml/mlflow/0
creation_time: 1773583831615
experiment_id: '0'
last_update_time: 1773583831615
lifecycle_stage: active
name: Default
workspace: default
