artifact_uri: file:///home/duds0/agents/projects/full-funnel-ai-analytics/ml/mlflow/950969965343710583/ceae082f05ea4464aac80d3c6e23374a/artifacts
end_time: 1773583837662
entry_point_name: ''
experiment_id: '950969965343710583'
lifecycle_stage: active
run_id: ceae082f05ea4464aac80d3c6e23374a
run_name: resilient-cow-22
source_name: ''
source_type: 4
source_version: ''
start_time: 1773583831840
status: 3
tags: []
user_id: duds0
