import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import mlflow
import mlflow.xgboost
from pathlib import Path
import os

# Paths
DATA_DIR = Path(__file__).parent.parent.parent / "data"
ML_DIR = Path(__file__).parent.parent

def load_data():
    """Load and preprocess data for lead scoring."""
    # Using fct_lead_scoring_features from DuckDB (simulated here from CSV)
    # In a real scenario, we'd pull from the warehouse
    features_df = pd.read_csv(DATA_DIR / "lead_scoring_features.csv")
    
    # Feature selection (matching api/main.py)
    y = features_df['is_won']
    X = features_df[['sessions', 'engaged_sessions', 'page_views', 'is_first_visit']]
    
    return train_test_split(X, y, test_size=0.2, random_state=42)

def train_model():
    """Train XGBoost model and track with MLflow."""
    X_train, X_test, y_train, y_test = load_data()
    
    # Set tracking URI to local file for now
    mlflow.set_tracking_uri(f"file://{ML_DIR}/mlflow")
    mlflow.set_experiment("Lead Scoring Optimization")
    
    with mlflow.start_run():
        # Hyperparameters
        params = {
            "max_depth": 5,
            "learning_rate": 0.1,
            "n_estimators": 100,
            "objective": "binary:logistic",
            "eval_metric": "auc",
            "random_state": 42
        }
        
        # Train
        model = xgb.XGBClassifier(**params)
        model.fit(X_train, y_train)
        
        # Predict
        preds = model.predict(X_test)
        pred_probs = model.predict_proba(X_test)[:, 1]
        
        # Metrics
        metrics = {
            "accuracy": accuracy_score(y_test, preds),
            "precision": precision_score(y_test, preds),
            "recall": recall_score(y_test, preds),
            "f1": f1_score(y_test, preds),
            "auc": roc_auc_score(y_test, pred_probs)
        }
        
        print(f"Model Metrics: {metrics}")
        
        # Log params and metrics
        mlflow.log_params(params)
        mlflow.log_metrics(metrics)
        
        # Log model
        mlflow.xgboost.log_model(model, "lead_scoring_xgb_model")
        
        # Save a local copy for the API
        model.save_model(ML_DIR / "lead_scoring_model.json")
        print(f"Model saved to {ML_DIR}/lead_scoring_model.json")

if __name__ == "__main__":
    # Ensure features exist (they should be generated by the mock data script)
    train_model()
